### ISSUE TITLE
This thing needs to be managed and advertised

### ISSUE THREAD

**Issue by pllim** [spacetelescope/style-guides#100]
A lot of STScI staff do not know we have style guides here.

Also, this repo has not been very active though there is much to do. Can we get some money to turn this into a properly managed project?

**Comment by arfon** [comment]
I agree. This definitely needs an owner.

/ cc @eteq @ivastar @stscicrawford who I've discussed this with in part too.

**Comment by pllim** [comment]
Discussed on 2019-12-20.
