### ISSUE TITLE
Ditch Travis CI as a recommended solution

### ISSUE THREAD

**Issue by pllim** [spacetelescope/style-guides#112]
Unless you want to pay them -- https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

**Comment by bhayden53** [comment]
It's unclear to me if the mentioned 1000 minutes of free linux env time applies to the spacetelescope org as a whole or each repo? 

Also unclear if we have any existing agreements with Travis, which according to other areas in the blog post, might make these changes irrelevant?

**Comment by sean-lockwood** [comment]
There may be a distinction between travis-ci.org and travis-ci.com?

**Comment by pllim** [comment]
`.org` is no more.

Not sure about the others, ask ITSD.

**Comment by pllim** [comment]
DMD Chief Engineer has announced the adoption of GitHub Actions on 2020-11-17.
