### ISSUE TITLE
Versioning Guide

### ISSUE THREAD

**Issue by stscicrawford** [spacetelescope/style-guides#28]
The [versioning guide ](https://github.com/spacetelescope/style-guides/blob/master/guides/software-versioning.md) is great and contains a lot of detail.  In the future, we may want to revisit it to take a look at having it focus more directly on the recommendations and saving some of the detail (especially the python 2.x which likely can be depreciated as we are recommending Python 3 only support -- but it is currently useful!)

**Comment by pllim** [comment]
Fixed by #118
