### ISSUE TITLE
Git flow docs

### ISSUE THREAD

**Issue by arfon** [spacetelescope/style-guides#32]
It's great that we've got a GitHub guide in here (✨ @bourque), however, I think the fork/PR workflow we're recommending is the wrong one for repositories under the `spacetelescope` organization.

Reasons I don't like forks:
- Forks are harder to back up: ITSD keeps backups of our Git(Hub) repositories. This is a contractual requirement. If we're all working in our own personal forks, then ITSD has to now back up all of the forks as well as the repositories under the `spacetelescope` organization.
- Forks are a usability nightmare: 
  - They require extra work to keep up to date with the parent (`git fetch upstream` etc).
  - If forks are of a public repository and more than one person wants to collaborate on a fork then you have to add each colleague to _your fork_
  - If forks are of a private repository then everyone watching the parent repository is _automatically subscribed to all of the fork activity by default_ (GitHub notification-hell)
- CI isn't enabled by default on forks - i.e. if the parent repository has Travis-CI turned on, then you have to open a pull request before Travis will start running tests. When pushing feature branches, CI can easily be enabled for all branches.

Instead of what we currently have in the GitHub workflow document, we propose the following:

**When STScI staff are working on an STScI-owned project, staff should push feature branches to a shared repository rather than working on personal forks**

Reasons I often hear against a feature-branch-on-a-shared-repository proposal:

- Equality of experience: If we have STScI staff pushing feature branches and non-STScI staff having to fork an open source repository then they have a different user experience. 
- People like to work privately: Forks are good because they are 'private'. IMO within an organization, this isn't a great reasons. I think we want **more transparency** in the workplace.
- I don't like cluttering up the main repository with lots of branches...
- What if people overwrite `master`? GitHub's [branch protection](https://help.github.com/articles/about-protected-branches/) should help us out here.

/ cc @eteq @bourque @stscicrawford (i.e. folks I've already discussed this with at least in part)

**Comment by bourque** [comment]
I'm not sure we ever came to a concrete decision about how to modify the [git Workflow](https://github.com/spacetelescope/style-guides/blob/master/guides/git-workflow.md) style guide to incorporate other workflows (or if we even want to do this).

@dpnemergut has some great slides on a release-driven git workflow (i.e. [`gitflow`](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)) from the Advanced git Training Workshop (see attached), and it seems that this workflow is used/would be useful for several groups at ST.  Perhaps we should describe this workflow (or at least link to it) in this style guide as a release-driven alternative to the already-described forking workflow. 

[Advanced Git.pdf](https://github.com/spacetelescope/style-guides/files/2962776/Advanced.Git.pdf)

**Comment by dpnemergut** [comment]
Details about the gitflow model can be found [in this post by Vincent Driessen](https://nvie.com/posts/a-successful-git-branching-model/). It can be used together with forking by setting the 'develop' branch to be the default in the main repo. People's forks can be used to create feature branches which are then pull requested to be merged back into the 'develop' branch of the main repo.

If you decided to forgo forking then all branches other than feature branches can be locked down to admins and pull requests must be created to merge code into them.

**Comment by arfon** [comment]
On reflection branches vs forks is not a hill I'm willing to die on so I'm happy to close this as a `wont-fix`. That said, if anyone is suitably motivated at some point, I think it might be worth noting somewhere in this guide that alternative workflows exist.

**Comment by pllim** [comment]
> On reflection branches vs forks is not a hill I'm willing to die on

Haha! Wise choice.

**Comment by bourque** [comment]
With fear of opening up a heated argument again, I would like to (re)request that we modify the `git` workflow docs to offer two options, a branching workflow and a forking workflow, with appropriate descriptions and pros/cons of each model.  I am happy to make those changes.  

The reason that I would like to do this (and do it soon) is that @shanosborne and myself are about to demand that INS JWST ancillary tool teams provide (or reference) a documented `git` workflow as part of our Tier 2 standards (more information about that effort here: https://github.com/spacetelescope/ins-jwst-community-software).  It would be great if INS teams could simply point to the `git` workflow docs here and simply say "we are using the branching model" or "we are using the forking model", instead of creating redundant documentation.  

Unless anyone has strong objections to this, I intend to open a PR to this repo within the next few weeks that adds a section for the branching model.
