### ISSUE TITLE
Release process and astroconda

### ISSUE THREAD

**Issue by stscicrawford** [spacetelescope/style-guides#49]
Related to #12, but we do need a page with details about how to do a release so that it is easily included in astroconda

**Comment by pllim** [comment]
cc @rendinam

**Comment by pllim** [comment]
For https://github.com/spacetelescope/style-guides/blob/master/guides/github-repositories.md#releases , in addition to GitHub release, AstroConda (as mentioned above) and PyPI are also recommended for Python packages.

**Comment by pllim** [comment]
@sean-lockwood , so there is an issue open about this after all.
