### ISSUE TITLE
Move maintainers to repo description?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/style-guides#51]
"An opinionated guide to setting up STScI-owned GitHub repositories maintained by @spacetelescope/style-gurus "

Inspired by https://github.com/astropy/package-template/

p.s. I am talking about possibly removing `CODEOWNERS` file.

**Comment by arfon** [comment]
> Move maintainers to repo description?

Can we not have it duplicated? The `CODEOWNERS` file can help identify reviewers/owners of specific style guides (see GitHub docs): https://help.github.com/articles/about-codeowners/

**Comment by pllim** [comment]
Oh I did not know about this feature. Thanks!

**Comment by pllim** [comment]
Duplicate is fine. Or feel free to close if this does not make sense.

**Comment by pllim** [comment]
I think about this more and agree that `CODEOWNERS` is more useful.
