### ISSUE TITLE
add mention of box as the currently-recommended solution for "intermediate" data

### ISSUE THREAD

**Issue by eteq** [spacetelescope/style-guides#65]
A discussion with ITSD lead to the conclusion that the best current solution to recommend here for the  is to tell internal user to put things on box and use a public link. Medium-term we'll develop a redirect tool that lets it instead be a more descriptive URL, but since the backing store will likely be Box, we can stick with that as the immediate recommendation.  Need to update the "data guide" to reflect this.

cc @stscicrawford 

EDIT: Also see https://jira.stsci.edu/browse/JUSI-26

**Comment by eteq** [comment]
Note that this approach was used for https://github.com/spacetelescope/da5-notebooks fairly successfully.  So we should probably document it based on that approach. There's a README in the box folder for this now... @larrybradley or @stscicrawford, should we put that here you think?

**Comment by sosey** [comment]
Is there any information available about why git lfs isn't viable?

**Comment by pllim** [comment]
@eteq , does this close https://jira.stsci.edu/browse/JUSI-26 ?
