### ISSUE TITLE
Team names: hyphens or whitespace?

### ISSUE THREAD

**Issue by jamienoss** [spacetelescope/style-guides#69]
Do we have a convention for team names? I guess this is slightly related to #10 and thus a team name should use a hyphen over an underscore, however, should we use a hyphen or whitespace?

**Comment by arfon** [comment]
I think spaces are fine (perhaps preferred for readability?). GitHub turns these into hyphenated team names anyway:

<img width="1030" alt="screen_shot_2018-11-30_at_9_47_20_am" src="https://user-images.githubusercontent.com/4483/49295984-1716d480-f485-11e8-8573-d4bef7488ab8.png">
