### ISSUE TITLE
Testing workflows

### ISSUE THREAD

**Issue by stscicrawford** [spacetelescope/style-guides#7]
Add information about testing workflows.

**Comment by pllim** [comment]
cc @bhilbert4

**Comment by pllim** [comment]
Testing can cover several things:

* Unit tests
* Regression tests
* PEP 8 (Python)
* Doc build (e.g., Python + Sphinx)
* Coverage

**Comment by pllim** [comment]
Also mention different CI services to choose from:

* Travis CI: Lightweight tests that don't exceed quotas for size and timing. Available for testing under Linux or OSX. Also see https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps (i.e., using travis-ci.com vs travis-ci.org ).
* Jenkins: In-house support. Virtually unlimited (unless you are very crazy). Has access to Artifactory. Linux only.
* Appveyor: Has quota like Travis. Running tests on Windows.
* CircleCI, etc.

**Comment by sean-lockwood** [comment]
@pllim I might not understand the scope of this guide, but isn't the Institute trying to limit CI tools to Jenkins (for internal projects) and Travis CI (for outside collaborative projects)?

**Comment by pllim** [comment]
And links to `pytest` resources.And some plugins that might be useful for `pytest`:

* https://github.com/astropy/pytest-astropy
* https://github.com/spacetelescope/ci_watson

**Comment by pllim** [comment]
Also guideline for when to bundle test data with the package, and when to use "big data" solution?

**Comment by stscicrawford** [comment]
I've assigned @pllim to take a first draft.   After that is available, we can then iterate on it and add more matirial

**Comment by pllim** [comment]
@drdavella , want to be co-author? 😉

**Comment by drdavella** [comment]
Sure, I'm happy to help and/or review.

**Comment by pllim** [comment]
@stscicrawford , is there a deadline for this... :grimacing:
