### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by stscicrawford** [spacetelescope/style-guides#8]
Guidelines for setting up jenkins and travis and openCI

**Comment by stscicrawford** [comment]
This following should be included for v1.0:

- [ ] Travis vs. Jenkins
- [ ] How to run travis and link to the travis docs
- [ ] How to run Jenkins  (for right now, come talk to DMD/ITSD) and link to the jenkins docs
- [ ] Adding example travis/jenkins files to the template

These should not be exhaustive but some high level pointers to what to do.

**Comment by pllim** [comment]
Apparently GitLab people also use OpenCI now. FYI.
