### ISSUE TITLE
Testing style guide: Discourage Travis CI, find replacement?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/style-guides#87]
Travis CI not looking good since its acquisition by Idera.

https://www.reddit.com/r/programming/comments/atjltu/layoffs_at_travis_ci_their_team_was_being/

**Comment by arfon** [comment]
Yes, we might want to. Suggest having this discussion in a non-public thread?

**Comment by pllim** [comment]
Sure. Let me know where. Thanks.
