### ISSUE TITLE
Notebook style guide: Footer instruction confusing

### ISSUE THREAD

**Issue by pllim** [spacetelescope/style-guides#92]
https://github.com/spacetelescope/style-guides/blob/master/guides/jupyter-notebooks.md#footer says we need a footer with logo, but does not say how it should be implemented. As a result, we have spacetelescope/notebooks#71.

There needs to be a clear instruction on how the logo should be included, preferably in a way that does not require each notebook to provide its own logo file.

**Comment by kjbrooks** [comment]
I ran into the same question that @pllim has pointed out in this issue, so I want to upvote it. 

Additionally, having a template notebook that implements the recommendations made in https://github.com/spacetelescope/style-guides/blob/master/guides/jupyter-notebooks.md would be incredibly helpful and would resolve this issue.
